networks:
  pokemon-net:
    driver: bridge

services:
  pokemon-database:
    image: "pokemon-database"
    build:
      context: ./database/
    container_name: pokemon-database
    environment:
      - MYSQL_USER=exsuslabs
      - MYSQL_PASSWORD=exsuslabs
      - MYSQL_DATABASE=pokemon
      - MYSQL_ROOT_PASSWORD=1  
    healthcheck:
          test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
          timeout: 20s
          retries: 1
    ports:
      - "8080:8080"
    networks:
      - pokemon-net

  pokemon-backend:
    image: "pokemon-backend"
    build:
      context: ./backend/
    container_name: pokemon-backend
    environment:
      - FLASK_APP=main.py
    ports:
      - "5000:5000"
    depends_on:
      pokemon-database:
        condition: service_healthy

    networks:
      - pokemon-net
